/*
 * EqotyScan - Free software to scan potential long/short stock
 * 
 * Copyright (C) 2016 Susan Chern <olivegreen48@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package EquotyScan;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author schern
 */
public class EquotyScan extends JFrame {

    /**
     * Creates new form EquotyScan
     */
    public EquotyScan() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        uPatternBtn = new java.awt.Button();
        WAbtn = new java.awt.Button();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Equity Scan Tools");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 153, 102));
        setForeground(new java.awt.Color(255, 255, 255));
        setIconImage(Toolkit.getDefaultToolkit().getImage("/images/sm_Icon.png"));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        uPatternBtn.setActionCommand("Scan Unusual Pattern");
        uPatternBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        uPatternBtn.setLabel("Scan Unusual Pattern");
        uPatternBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uPatternActionPerformed(evt);
            }
        });

        WAbtn.setActionCommand("Scan MA");
        WAbtn.setLabel("Scan Moving Average");
        WAbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoveAvgActionPerformed(evt);
            }
        });

        jLabel1.setText("Step 1: Select sector ");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(sectors));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Step 2: Select tool to start");

        jLabel3.setText("(sectors reference yahoo finance)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3))
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(uPatternBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WAbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(4, 4, 4)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(WAbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(uPatternBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(139, Short.MAX_VALUE))
        );

        uPatternBtn.getAccessibleContext().setAccessibleName("");
        WAbtn.getAccessibleContext().setAccessibleName("Scan MA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

   
    //Invoked when the user attempts to close the window from the window's system menu.
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
         System.out.println("window closed, force kill process now!");
         System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    //Invoke when user click on exit from form
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

         System.out.println("window closing, force kill process now!");
         System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void MoveAvgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoveAvgActionPerformed
        if(checkSector() == false)  return;
        String infoMessage = sector + " sector MA trend change scan request received. Click on OK to continue";
        String titleBar = "MA Scan";
        Util.infoDialog(titleBar, infoMessage);
        JOptionPane Jop = new JOptionPane();
        MAvgScan mva = new MAvgScan();
        //mva.setVisible(true);
    }//GEN-LAST:event_MoveAvgActionPerformed

    private void uPatternActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uPatternActionPerformed

        if(checkSector() == false)  return;
        String infoMessage = sector + " sector pattern-scan request received. Click on OK to continue";
        String titleBar = "Pattern Scan";
        Util.infoDialog(titleBar, infoMessage);
        JOptionPane Jop = new JOptionPane();
        
        POption uPattern = new POption();
        if(img !=null){
            uPattern.setIconImage(img);
        }
        uPattern.setVisible(true);

    }//GEN-LAST:event_uPatternActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        sector = (String)jComboBox1.getSelectedItem();
        RWCSVFile.sector_selected = sector;
        System.out.println("sector selected: " + sector);
        if(sector.equals("All")){
            Util.infoDialog("Sector selection", "Warning! You select to scan all sectors! Performance trade-off on this selection.");
        }
        
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private boolean checkSector(){
        if(sector==null || sector.equals("Select one")){
            Util.infoDialog("Scan validation", "Error: No sector selected! Please first a sector to continue");
            return false;
        }
        return true;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        //configuration checking
        RWCSVFile csvObj = new RWCSVFile();
        
        if(csvObj.DataFileExist() == true){
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
             * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(EquotyScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(EquotyScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(EquotyScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(EquotyScan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>    
                   //read in data file and generate complete list
                    csvObj.genList();
                   final EquotyScan mPage = EquotyScan.getInstance();
                    mPage.init();
                    
                    if(img !=null){
                        mPage.setIconImage(img);
                    }
                    mPage.setVisible(true);        
        }else   
            System.exit(0);
    }

    
    /**
     * Returns EquotyScan as singleton.
     * 
     * @return EquotyScan as singleton
     */
    public static EquotyScan getInstance() {
        final EquotyScan INSTANCE = new EquotyScan();
        return INSTANCE;
    }
    
     private void init(){
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }
        catch(ClassNotFoundException | IllegalAccessException | InstantiationException | UnsupportedLookAndFeelException exp){
            System.out.println("error on init. msg: " + exp.getMessage());
        }
        
        initComponents();
    }
     
     
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button WAbtn;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private java.awt.Button uPatternBtn;
    // End of variables declaration//GEN-END:variables

    private static Image img = Util.getThumbnailIncon();
    String[] sectors = Util.sectors;
    String sector=null;
    

}
