/*
 * EqotyScan - Free software to scan potential long/short stock
 * 
 * Copyright (C) 2016 Susan Chern <olivegreen48@gmail.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package EquotyScan;

import javax.swing.SwingWorker;
import javax.swing.UIManager;

/**
 *
 * @author schern
 */
public class POption extends javax.swing.JFrame {

    /**
     * Creates new form POption
     */
    public POption() {
        /* Create and display the form */
        //final POption mPage = POption.getInstance(); 
        
       initComponents();
        /*
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               final POption mPage = POption.getInstance();                             
                mPage.init();
                mPage.setVisible(true);
                
            }
        });
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lastDateBtn = new java.awt.Button();
        jSeparator1 = new javax.swing.JSeparator();
        dateReq = new javax.swing.JTextField();
        reqDateBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        title = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lastDateBtn.setActionCommand("Scan Last Work Date");
        lastDateBtn.setLabel("Scan Last Work Date");
        lastDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastDateBtnActionPerformed(evt);
            }
        });

        reqDateBtn.setLabel("Scan this Date");
        reqDateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reqDateBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("(format: YYYYMMDD)");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Select either \" last work date\" or specify it:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dateReq, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(reqDateBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lastDateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel1)))
                .addContainerGap(118, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(lastDateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateReq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reqDateBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(87, Short.MAX_VALUE))
        );

        lastDateBtn.getAccessibleContext().setAccessibleName("");
        dateReq.getAccessibleContext().setAccessibleName("");
        reqDateBtn.getAccessibleContext().setAccessibleName("");

        title.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("Unusual Pattern Stock Options Scanner - Long");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(title)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lastDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastDateBtnActionPerformed
        //get last work date
        lastMarketDate lmd = new lastMarketDate();
        date2Check = lmd.getLastWorkDate();
        
        ScanNow myscan = new ScanNow(date2Check);
        myscan.setVisible(true);
        
    }//GEN-LAST:event_lastDateBtnActionPerformed

    private void reqDateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reqDateBtnActionPerformed
        
        date2Check = dateReq.getText().toString();
        ScanNow myscan = new ScanNow(date2Check);
        myscan.setVisible(true);
        
    }//GEN-LAST:event_reqDateBtnActionPerformed

    /*
    private void tmp(String date){
        float a="0.12", b="1.335f, d=1.965f;
        String c="0.55";
        resultList rl = new resultList();
        Map<String, resultData> map = rl.getList();
        resultData rd = new resultData("aapl", a,b, c, d);
                    //scanOutput.add(rd);
        map.put(rd.getTicker(), rd);
         String msg;
               Boolean wStatus = new RWCSVFile().writeCSVFile(date);
               JFrame frame = new JFrame("Dialog");
               if(wStatus == true)
                    JOptionPane.showMessageDialog(frame,"Save to CSV file successfully.");
               else
                   JOptionPane.showMessageDialog(frame,"Save to CSV file failed.");
    }
    */
    //Invoked when the user attempts to close the window from the window's system menu.
    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
         System.out.println("window closed, force kill process now!");
         System.exit(0);
    }//GEN-LAST:event_formWindowClosed

    //Invoke when user click on exit from form
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

         System.out.println("window closing, force kill process now!");
         System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    

     //return date with dash format from YYYYMMDD
    private String breakDate(String noDash){
        String y = noDash.substring(0, 4);
        String m = noDash.substring(3, 6);
        String d = noDash.substring(5, 8);
        String dashDate = y + "-" + m + "-" + d;
        return dashDate;
    }
    /**
     * Returns POption as singleton.
     * 
     * @return POption as singleton
     */
    public static POption getInstance() {
        final POption INSTANCE = new POption();
        return INSTANCE;
    }
    
     private void init(){
         System.out.println("in init");
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }
        catch(Exception exp){
            System.out.println("error on init. msg: " + exp.getMessage());
        }
        
        initComponents();
    }
     
     
     
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField dateReq;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.Button lastDateBtn;
    private javax.swing.JButton reqDateBtn;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

    private static String date2Check;
    //static MsgConsole mc;
   // static SwingWorker<String, Void> mc;
    //static MsgCollector msgC;

}
